import type { MetricSeed } from "../types";

export const psychologySeeds: MetricSeed[] = [
  { id: "p-wm-digit-span", name: "Working memory digit span forward (adults, typical)", category: "psychology", low: 5, high: 8, unit: "digits", context: "Phone number chunking.", explanation: "Miller's magical number is optimistic for raw spans.", spacing: "linear" },
  { id: "p-simple-rt", name: "Simple reaction time (young adult, means)", category: "psychology", low: 190, high: 260, unit: "ms", context: "One button.", explanation: "Means vary by modality; gaming mice don't make you superhuman.", spacing: "linear" },
  { id: "p-choice-rt", name: "Choice reaction time (2AFC)", category: "psychology", low: 280, high: 420, unit: "ms", context: "Hick's law neighborhood.", explanation: "More choices → slower; UI hates overwhelming menus.", spacing: "linear" },
  { id: "p-iq-sd", name: "IQ score standard deviation (most normed tests)", category: "psychology", low: 14, high: 16, unit: "points", context: "σ = 15 lore.", explanation: "Most common norm SD is 15; some use 16.", spacing: "linear" },
  { id: "p-test-retest-g", name: "g‑loaded test stability (few months)", category: "psychology", low: 0.85, high: 0.95, unit: "r", context: "Not destiny.", explanation: "High reliability doesn't mean fair or meaningful for decisions.", spacing: "linear" },
  { id: "p-big5-reliability", name: "Cronbach's α (Big Five facet scales, decent)", category: "psychology", low: 0.75, high: 0.9, unit: "α", context: "Internal consistency.", explanation: "Short scales cheat reliability; long inventories inflate it.", spacing: "linear" },
  { id: "p-morality-foundations-count", name: "Moral foundations in original taxonomy", category: "psychology", low: 5, high: 5, unit: "foundations", context: "Haidt-ish story.", explanation: "Later work expands/critiques; five is quiz‑famous.", spacing: "linear" },
  { id: "p-milgram-obedience", name: "Maximum shock label in Milgram series (famous)", category: "psychology", low: 400, high: 450, unit: "V labeled", context: "Ethics changed.", explanation: "Studies vary; \"450 V\" is the infamous ceiling label in many retellings.", spacing: "linear" },
  { id: "p-stroop-slowdown", name: "Stroop interference slowdown (typical lab)", category: "psychology", low: 80, high: 200, unit: "ms", context: "Color words.", explanation: "Automatic reading battles color naming.", spacing: "linear" },
  { id: "p-attention-blink", name: "Attention blink duration window", category: "psychology", low: 200, high: 500, unit: "ms", context: "RSVP targets.", explanation: "Second target inside ~half second often missed.", spacing: "linear" },
  { id: "p-iat-effect-ms", name: "IAT compatibility effect (implicit bias tasks, variable)", category: "psychology", low: 80, high: 250, unit: "ms", context: "Interpretation wars.", explanation: "Effect sizes differ by domain; social cognition is messy.", spacing: "linear" },
  { id: "p-forgetting-curve-day1", name: "Retention without review (Ebbinghaus vibe, day 1)", category: "psychology", low: 35, high: 60, unit: "% remembered", context: "Nonsense syllables not your life.", explanation: "Meaningful material behaves differently; spacing effect still king.", spacing: "linear" },
  { id: "p-sleep-debt-performance", name: "Performance drop (simple vigilance) after ~17-19h awake", category: "psychology", low: 20, high: 45, unit: "% vs rested", context: "Comparable to BAC debates.", explanation: "Sleep deprivation impairs like intoxication in some tasks.", spacing: "linear" },
  { id: "p-weber-fraction-brightness", name: "Weber fraction for brightness (very rough)", category: "psychology", low: 0.02, high: 0.08, unit: "ΔI/I", context: "Just noticeable difference.", explanation: "Sensory systems differ; mid‑ranges easier than extremes.", spacing: "linear" },
  { id: "p-fitts-id", name: "Fitts' index of difficulty (GUI \"easy\" corner target)", category: "psychology", low: 0.8, high: 2.5, unit: "bits", context: "log₂(D/W+1).", explanation: "Big targets close to cursor score low ID; good UX wins.", spacing: "linear" },
  { id: "p-nps-promoter", name: "NPS promoter score threshold", category: "psychology", low: 9, high: 10, unit: "0–10", context: "Marketing thermometer.", explanation: "9–10 are promoters in classic NPS; critics abound.", spacing: "linear" },
  { id: "p-nps-detractor", name: "NPS detractor threshold", category: "psychology", low: 0, high: 6, unit: "0–10", context: "Haters counted.", explanation: "0–6 detractors in classic scheme.", spacing: "linear" },
  { id: "p-flow-challenge-skill", name: "Challenge/skill balance ratio (flow channel lore)", category: "psychology", low: 1.0, high: 1.12, unit: "challenge:skill", context: "Csikszentmihalyi story.", explanation: "Slightly above skill pushes growth; too far → anxiety.", spacing: "linear" },
];
